[2023-02-28 14:33:35,160] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [queued]>
[2023-02-28 14:33:35,238] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [queued]>
[2023-02-28 14:33:35,247] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-28 14:33:35,252] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-02-28 14:33:35,260] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-28 14:33:35,369] {taskinstance.py:1377} INFO - Executing <Task(SparkSubmitOperator): spark_submit> on 2023-02-28 14:33:24.326607+00:00
[2023-02-28 14:33:35,475] {standard_task_runner.py:52} INFO - Started process 347 to run task
[2023-02-28 14:33:35,484] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'avg_product_price', 'spark_submit', 'manual__2023-02-28T14:33:24.326607+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/avg_product_price.py', '--cfg-path', '/tmp/tmped7z5h3i', '--error-file', '/tmp/tmpn_i0ranm']
[2023-02-28 14:33:35,504] {standard_task_runner.py:80} INFO - Job 2: Subtask spark_submit
[2023-02-28 14:33:35,844] {task_command.py:370} INFO - Running <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [running]> on host 955b42728ca0
[2023-02-28 14:33:36,928] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ayyoub
AIRFLOW_CTX_DAG_ID=avg_product_price
AIRFLOW_CTX_TASK_ID=spark_submit
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T14:33:24.326607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T14:33:24.326607+00:00
[2023-02-28 14:33:36,999] {base.py:68} INFO - Using connection ID 'spark-hadoop' for task execution.
[2023-02-28 14:33:37,006] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py
[2023-02-28 14:34:00,574] {spark_submit.py:495} INFO - python3: can't open file '/hadoop-latihan/map_reduce/spark/average_price.py': [Errno 2] No such file or directory
[2023-02-28 14:34:00,632] {spark_submit.py:495} INFO - 23/02/28 14:34:00 INFO ShutdownHookManager: Shutdown hook called
[2023-02-28 14:34:00,640] {spark_submit.py:495} INFO - 23/02/28 14:34:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-ba15b8b8-01b5-4f8a-8a7c-7c8fb99c3ff5
[2023-02-28 14:34:00,818] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py. Error code is: 2.
[2023-02-28 14:34:00,860] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=avg_product_price, task_id=spark_submit, execution_date=20230228T143324, start_date=20230228T143335, end_date=20230228T143400
[2023-02-28 14:34:00,920] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task spark_submit (Cannot execute: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py. Error code is: 2.; 347)
[2023-02-28 14:34:01,048] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-28 14:34:01,144] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
