[2023-02-28 14:39:02,676] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [queued]>
[2023-02-28 14:39:02,690] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [queued]>
[2023-02-28 14:39:02,691] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-28 14:39:02,692] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-02-28 14:39:02,693] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-28 14:39:02,785] {taskinstance.py:1377} INFO - Executing <Task(SparkSubmitOperator): spark_submit> on 2023-02-28 14:33:24.326607+00:00
[2023-02-28 14:39:02,791] {standard_task_runner.py:52} INFO - Started process 499 to run task
[2023-02-28 14:39:02,795] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'avg_product_price', 'spark_submit', 'manual__2023-02-28T14:33:24.326607+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/avg_product_price.py', '--cfg-path', '/tmp/tmp75immbm8', '--error-file', '/tmp/tmp7_0jqtxx']
[2023-02-28 14:39:02,797] {standard_task_runner.py:80} INFO - Job 3: Subtask spark_submit
[2023-02-28 14:39:02,873] {task_command.py:370} INFO - Running <TaskInstance: avg_product_price.spark_submit manual__2023-02-28T14:33:24.326607+00:00 [running]> on host 955b42728ca0
[2023-02-28 14:39:02,973] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ayyoub
AIRFLOW_CTX_DAG_ID=avg_product_price
AIRFLOW_CTX_TASK_ID=spark_submit
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T14:33:24.326607+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T14:33:24.326607+00:00
[2023-02-28 14:39:02,985] {base.py:68} INFO - Using connection ID 'spark-hadoop' for task execution.
[2023-02-28 14:39:02,987] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py
[2023-02-28 14:39:07,656] {spark_submit.py:495} INFO - python3: can't open file '/hadoop-latihan/map_reduce/spark/average_price.py': [Errno 2] No such file or directory
[2023-02-28 14:39:07,679] {spark_submit.py:495} INFO - 23/02/28 14:39:07 INFO ShutdownHookManager: Shutdown hook called
[2023-02-28 14:39:07,682] {spark_submit.py:495} INFO - 23/02/28 14:39:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-ec2c84a4-3ea6-4daa-9f53-86a53c37c8cc
[2023-02-28 14:39:07,805] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py. Error code is: 2.
[2023-02-28 14:39:07,813] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=avg_product_price, task_id=spark_submit, execution_date=20230228T143324, start_date=20230228T143902, end_date=20230228T143907
[2023-02-28 14:39:07,844] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task spark_submit (Cannot execute: spark-submit --master local[*] --name arrow-spark /hadoop-latihan/map_reduce/spark/average_price.py. Error code is: 2.; 499)
[2023-02-28 14:39:07,861] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-28 14:39:07,980] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
